# Generated by Django 4.2.17 on 2024-12-14 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('langchain_app', '0002_company_jobinfo_recruitment_delete_generateddata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetterGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoverLetterOutline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('outline', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='langchain_app.jobinfo')),
            ],
        ),
    ]
