# Generated by Django 4.2.17 on 2024-12-15 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('langchain_app', '0003_coverletterguide_coverletteroutline'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetterPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('outline', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecruitJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('required_skills', models.TextField(blank=True, null=True)),
                ('soft_skills', models.TextField(blank=True, null=True)),
                ('key_strengths', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobinfo',
            name='recruitment',
        ),
        migrations.RemoveField(
            model_name='company',
            name='industry',
        ),
        migrations.AddField(
            model_name='recruitment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitments', to='langchain_app.company'),
        ),
        migrations.DeleteModel(
            name='CoverLetterOutline',
        ),
        migrations.DeleteModel(
            name='JobInfo',
        ),
        migrations.AddField(
            model_name='recruitjob',
            name='recruitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruit_jobs', to='langchain_app.recruitment'),
        ),
        migrations.AddField(
            model_name='coverletterprompt',
            name='recruit_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letter_prompts', to='langchain_app.recruitjob'),
        ),
    ]
