# Generated by Django 4.2.17 on 2025-02-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langchain_app', '0005_company_industry_recruitjob_key_roles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitjob',
            name='recruitment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='recruitment_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
