# Generated by Django 4.2.17 on 2025-02-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langchain_app', '0006_recruitjob_recruitment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverletterprompt',
            name='limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='jss_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
