# Generated by Django 4.2.17 on 2025-03-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langchain_app', '0007_coverletterprompt_limit_recruitment_jss_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, null=True),
        ),
    ]
