# Generated by Django 4.2.17 on 2024-12-21 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='starexperience',
            name='raw_experience',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='star_experiences', to='user_experience.rawexperience'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rawexperience',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='rawexperience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_experiences', to=settings.AUTH_USER_MODEL),
        ),
    ]
