# Generated by Django 4.2.17 on 2024-12-21 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_experience', '0002_starexperience_raw_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawexperience',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raw_experience', to=settings.AUTH_USER_MODEL),
        ),
    ]
