# Generated by Django 4.2.17 on 2024-12-22 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('langchain_app', '0005_company_industry_recruitjob_key_roles_and_more'),
        ('user_experience', '0003_alter_rawexperience_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCoverLetter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recommended_starexperience', models.JSONField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('draft', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prompts', to='langchain_app.coverletterprompt')),
                ('recruit_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to='langchain_app.recruitjob')),
                ('selected_starexperience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_cover_letters', to='user_experience.starexperience')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'recruit_job', 'prompt')},
            },
        ),
    ]
